POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Building Scalable Microservices with Node.js",
  "author": "Sarah Mitchell",
  "url": "https://devblog.tech/microservices-nodejs",
  "likes": 42
}